#!/bin/sh
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

temp=$(basename $0)
tmp_file=$(mktemp -q /tmp/${temp}.XXXXXX)
if [ $? -ne 0 ]; then
    if [ -n "$1" ]; then
        echo "$0: Can't create temp file, using vim instead..."
        vim "$1"
        exit $?
    else
        echo "$0: Can't create temp file, aborting."
        exit $?
        fi
    fi
echo "cat > $tmp_file > $1" >& 2
cat > "$tmp_file"
ret=$?
echo "" >&2
if [ $ret -eq 0 ]; then
    if [ -n "$1" ]; then
        cat "$tmp_file" > "$1"
        ret=$?
    else
        cat "$tmp_file"
        ret=$?
        fi
    rm -rf "$tmp_file"
    fi
exit $ret
